### ISSUE TITLE
When trying to convert potions (any) in jewels, it doesn't work! My game version is 1.06

### ISSUE THREAD

**Issue by LordTreufeldt** [WalterCouto/D2CE#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WalterCouto** [comment]
Can you attach your d2s file so I can process it.

**Comment by LordTreufeldt** [comment]
> Can you attach your d2s file so I can process it.

[Spartacus (1).zip](https://github.com/WalterCouto/D2CE/files/8099425/Spartacus.1.zip) - D2 LoD Save
[Spartacus.zip](https://github.com/WalterCouto/D2CE/files/8099375/Spartacus.zip) - D2R Save

O herói anexado é um Bárbaro "offline" com atributos normais de qualquer bárbaro de nível 12, mas tanto com itens no inventário quanto equipado com itens "super poderosos"!

No início quando o bárbaro estava no nível 1 o teu editor não convertia as "Full Rejuvenation Potions" em Gemas, que foi a primeira tentativa que fiz de converter itens com este editor.

E agora depois de chegar no nível 12 com este bárbaro, o editor nem abre mais o arquivo, dizendo que tem itens corrompidos!

**Comment by LordTreufeldt** [comment]
O arquivo anterior Spartacus.d2s (D2R Save) não estava sendo aberto no jogo, falha minha! Parece que eu havia enviado uma cópia corrompida ou algo semelhante ...

Estou enviando o arquivo funcional, já com o mesmo personagem, no nível 16:

[Spartacus.zip](https://github.com/WalterCouto/D2CE/files/8119125/Spartacus.zip)

**Comment by WalterCouto** [comment]
O arquivo Spartacus.d2s possui itens não suportados "Full Health
Potion" e "Full Mana Potion". Eu Corrigi o problema de lidar com esses itens.

Tente usar a versão 2.1.3.
