### ISSUE TITLE
BTDiablo

### ISSUE THREAD

**Issue by WhoMikeJones666** [WalterCouto/D2CE#10]
Can you please add support for BT Diablo?

**Comment by WalterCouto** [comment]
Version 2.21 add initial support for D2R Mods. BT Diablo being one example of a D2R Mod that should work now.  One task left to do is take into account additional mercenary slots.

**Comment by WalterCouto** [comment]
@WhoMikeJones666 release-2.2.2 should add full support for D2R Mods like BT Diablo or Rebirth
