### ISSUE TITLE
Cannot add items on 2.6 (1.3.70409)

### ISSUE THREAD

**Issue by subzero364** [WalterCouto/D2CE#11]
Adding any item to the inventory using the editor on a 2.6 (1.3.70409) character appears to corrupt the save file.  Attempting to enter an offline game results in "Failed to join game" message. This was replicated on two fresh offline characters. Waypoints and quest progress can be added without issue. I know this was updated for 2.6 PTR at least, but something seems to have changed since then.  Is there any plan to update for 1.3.70409-PROD?

 OS: Windows 10

**Comment by WalterCouto** [comment]
https://github.com/WalterCouto/D2CE/raw/main/D2Editor.exe

Try the above. It has not yet been released, but contains an update to the item properties where 2.6 PTR changed the size of one of them without changing the file version.

**Comment by WalterCouto** [comment]
Fixed in Version 2.21
