### ISSUE TITLE
Here is an example of a .d2s that isn't opening by Editor, but loads normally in game

### ISSUE THREAD

**Issue by LordTreufeldt** [WalterCouto/D2CE#2]
Aqui está um exemplo de arquivo .d2s que não está sendo aberto pelo editor, mas que carrega normalmente no jogo:

[Loradiel.zip](https://github.com/WalterCouto/D2CE/files/8119052/Loradiel.zip)

Ao que parece, este char tem algum "Unique Item" no baú que está impedindo o editor de abrir o arquivo!

**Comment by WalterCouto** [comment]
Outros editors têm o mesmo problema, por exemplo https://d2s.dschu012.dev.

Todos nós estamos encontrando algo inesperado nas "magical properties". Eu Vou tentar encontrar o problema.

**Comment by LordTreufeldt** [comment]
Então Walter ... Depois do ocorrido com os saves, eu andei dando uma 
analisada no save que estava dando incompatibilidade com os editores, 
inclusive o teu.

No caso do savegame Loradiel.d2s, havia um "Unique Item" no baú que eu 
tinha importado, mas não criado. Importei de um pack na internet.  Esse 
item era uma "Unique Ancient Armor" só que ela estava com a atribuição 
de um outro Unique Item nível 2, uma adaga unique se não me engano, a 
Rixot's Queen. Então creio eu que a rotina que trata os itens talvez 
estivesse procurando a assinatura da armadura mas encontrava os bytes da 
adaga! E aí dá bode ao tentar abrir o save, talvez pelo comprimento dos 
bytes que definem o item, não sei, só uma divagação ...

Tenta analisar por aí ... Depois que joguei fora essa armadura com 
assinatura de adaga, o save voltou a funcionar e abrir normalmente!

Só que isso pode ser um problema! O jogo D2R aceita um item com 
assinatura inválida, o que a meu ver, não deveria acontecer e o jogo 
deveria excluir esse item automaticamente.

Só lembrando que a versão que uso é 1.06xxx. Não sei se no patch atual 
2.4 é feita alguma validação da assinatura do item ...

Em 01/03/2022 10:00, WalterCouto escreveu:

**Comment by WalterCouto** [comment]
Eu encontrei o problema. Este item tem "realm data". Eu não encontrei muitas informações sobre como essa seção opcional é tratada e nenhum dos exemplos que encontrei continha essa seção, portanto eu nunca encontrei esse problema antes ou pude testar esse caso. As informações que encontrei indicavam que esta seção era de 96 bits, mas eu não tinha como testar se estava correto. Seu item mostra que a seção é de 128 bits, e usando isso, tudo é tratado corretamente. Seus characters são casos muito bons para D2R editors :).

Eu vou corrigir isso em breve.

**Comment by LordTreufeldt** [comment]
Legal. Aproveitando o encejo ... Existe a quantidade de soquetes do item,
mas precisa validar também no editor se o item tem o atributo mágico
"Increased Sockets", se não me engano, vai de 0 a 15. Tem alguns itens que
utilizo essa propriedade pra adicionar mais soquetes, pois no D2R o jogo
"capa" qualquer tentativa de aumentar a quantidade de soquetes somente pela
propriedade normal do item. Com "increased sockets" dá pra passar desse
limite. No caso, o teu editor está carregando somente as jewels ou gemas
que estão nos soquetes normais do item e não nos adicionais, beleza.

Abraço;

Em qua., 2 de mar. de 2022 às 11:10, WalterCouto ***@***.***>
escreveu:

**Comment by WalterCouto** [comment]
Fixed in release-2.1.5
