### ISSUE TITLE
Savegame Versions -> Converter

### ISSUE THREAD

**Issue by LordTreufeldt** [WalterCouto/D2CE#3]
Como o formato do savegame na versão 2.4 aparentemente foi ligeiramente alterado em relação à versão 2.3, gostaria de solicitar uma opção de menu, ou uma configuração do programa que permita gravar o savegame no formato antigo da versão 2.3 ou no formato novo da versão 2.4.

Enfim, se for possível adicionar a versão do savegame no editor seria ótimo!

**Comment by WalterCouto** [comment]
Isso é uma boa ideia. Vou adicionar isso em breve. Você pode experimentar com a compilação interna:: [https://github.com/WalterCouto/D2CE/blob/main/D2Editor.exe?raw=true](url)

No menu arquivo, escolha "Change Version".

**Comment by WalterCouto** [comment]
changes in version 2.1.6
