### ISSUE TITLE
Patch 2.5 Compatibility Issue

### ISSUE THREAD

**Issue by DeutscheOrden** [WalterCouto/D2CE#5]
Corrupt Diablo II character file detected. Invalid item inventory, when trying to open character file. 

No such issue before patch 2.5. 

After removing equipped amulet to shared stash, character file can be opened normally. Some set items, small charms may also cause this issue.

**Comment by WalterCouto** [comment]
Yes, there is an effort online to fix up the reading to accommodate the new properties.  Hopefully soon we'll have reversed the logic completely.

**Comment by WalterCouto** [comment]
fixed in version 2.1.7

**Comment by ZeDestructor** [comment]
While 2.1.7 does now open and correctly edit files, items acquired in patch 2.5 (after 2.4) do not show up in D2CE but do show up in game. This occurs in stash, shared stash, player inventory, hireling. I have not checked player held items and cube, but I expect they will be similar.

**Comment by WalterCouto** [comment]
fixed in version 2.1.9
