### ISSUE TITLE
Using the editor forcibly completes end of act quests

### ISSUE THREAD

**Issue by ZeDestructor** [WalterCouto/D2CE#6]
When used at all, the editor (since 2.1.7 at least) forcibly completes end of act quests when it should not do so.

**Comment by WalterCouto** [comment]
End of Acts quests are only completed when you have started the next Act to keep the game consistent.  Do you have an example of when the end of acts was completed when the next act was not started?

**Comment by humping-koala** [comment]
I'm having the same issue. It forcibly makes all completed and current quests up to the current act being marked as "You completed this quest in a previous game". I wanted to use this editor to simply reset my skills & stats, but it unfortunately marks my current quest (Act IV - Q3) as completed, which messes up the game state.

Here is my save file: [Diablo II Resurrected.messed_up.orig.zip](https://github.com/WalterCouto/D2CE/files/10179864/Diablo.II.Resurrected.messed_up.orig.zip)

Tested on the editor versions 2.1.5-2.1.9
Game: Diablo II Resurrected - Patch version 2.4

P.S. From your commit history I found the https://github.com/daidodo/diablo_edit repo, which is able to edit my save file without affecting the quests in a negative manner.

**Comment by WalterCouto** [comment]
Thaks for the file, it seems some character files may incorrectly mark Act IV complete and Act V introduced causing the logic that tries to maintain a consistent character file to fix up the quests in Act IV and enable the waypoint in Act V.  This is not common, but I have another example file with the same issue independent of yours, so fixed this case in 2.2.0

**Comment by arslan-charyyev** [comment]
Thank you very much!

**Comment by humping-koala** [comment]
Thank you very much!
