### ISSUE TITLE
Meus chars continuam dando mensagem de item corrompido!

### ISSUE THREAD

**Issue by LordTreufeldt** [WalterCouto/D2CE#7]
Olá.

Todos os meus chars "Single Player" continuam dando mensagem "invalid item in inventory". Os itens são "legítimos", mas com atributos hackeados.

Qual a finalidade de fazer um editor que não permite abrir caracteres com itens que tem stats hackeadas!? Nem precisa editor se for pra utilizar itens normais do jogo!

Em anexo abaixo um dos saves versão 2.5 que dá problema ao abrir.

![D2CEBug](https://user-images.githubusercontent.com/99281698/193311099-547d7463-d425-4172-ac09-7bd64162b2ba.jpg)

[Konan.zip](https://github.com/WalterCouto/D2CE/files/9686076/Konan.zip)

**Comment by ZeDestructor** [comment]
This is probably related to how 2.5 is saving items into inventories. I've got a similar issue that I've mentioned already in #5 (expecting it to be re-opened).

**Comment by WalterCouto** [comment]
Não se trata de itens normais vs hackeados. A comunidade que produz esses programas tem que adivinhar a lógica dos exemplos e esses vêm do jogo. Neste caso, um de seus itens hackeados usa os atributos "max lighting damage" e "max cold damage" sem usar o atributo "min damage". Esses atributos normalmente vêm em três: mínimo, máximo e quanto tempo" Parece que você pode especificar apenas o máximo. Este bug é todos os programas que suportam PTR 2.5 que eu tentei.

Vou corrigir isso em breve.

**Comment by WalterCouto** [comment]
fixed in release-2.1.9
