### ISSUE TITLE
Atributos dos Set Itens mostrados no Editor

### ISSUE THREAD

**Issue by LordTreufeldt** [WalterCouto/D2CE#8]
Olá.

Apenas uma sugestão ...

Quando mostrando os atributos de um SET item, o editor bem que poderia mostrar também os atributos adicionais da parte do SET em questão. Tipos alguns itens de alguns sets tem algum atributo individual adicional. Na foto abaixo, um exemplo do War Scepter "Milabrega Rod", hackeado obviamente :)

![Sugestion](https://user-images.githubusercontent.com/99281698/193643712-0e79c75f-f1b0-4f5d-a708-3dbbbda450cf.jpg)

Obrigado.

**Comment by WalterCouto** [comment]
fixed in release-2.2.0
